blogger_Blog_category:
    path:     /category
    defaults: { _controller: BloggerBlogBundle:Blog:category }

blogger_Blog_category_show:
    path:     /category/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:categoryShow }